Lesson 2, task 1
js-tasks-ru/js-20210921_hvostova-masha pull request #2
Opened 2021-09-27 09:33 UTC by KhMaria

2021-09-27 09:36 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-27 10:06 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArray.sort((a, b) => {
в данном решении есть дубликаты кода! От дубликатов следует избавиться

2021-09-27 10:06 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2021-09-27 18:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-27 18:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-27 18:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-09-28 12:23 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(arr, param = 'asc') {
good 👍

2021-09-28 12:23 UTC, dosandk approved these changes
good 👍

2021-09-30 13:43 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const fieldsValues = Object.values(fields);
эта операция лишняя, ведь мы получаем значения при вызове `Object.entries(obj)`

2021-09-30 13:43 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const fieldsValues = Object.values(fields);
эта операция лишняя, ведь мы получаем значения при вызове `Object.entries(obj)`

2021-09-30 13:43 UTC, dosandk approved these changes
решения приняты. Необходимо решить конфликты

2021-09-30 13:43 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-09-30 13:44 UTC, dosandk commented
@KhMaria необходимо решить конфликты

2021-10-01 13:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-01 14:26 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-01 16:11 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const fieldsPath = path.split(".");
👍 лайк за использование замыкания

2021-10-01 16:11 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +export function trimSymbols(string, size) {
good 👍

2021-10-01 16:12 UTC, dosandk approved these changes
good 👍

2021-10-02 07:54 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-02 13:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-10-04 13:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +export function invertObj(obj) {
good 👍

2021-10-04 13:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(set.keys());
в данном решении нет необходимости итерировать `Set` коллекцию, можно сразу передать ее в `Array.from` или использовать `spread-syntax: ...`

2021-10-04 13:30 UTC, dosandk approved these changes
good 👍

2021-10-05 10:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-05 10:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-05 10:30 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-05 16:13 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    delete this.generalChartInfo;
так делать не стоит, значения лучше переопределить/затереть а не удалять

2021-10-05 16:14 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    delete this.generalChartInfo;
ведь такая операция удалит свойство полностью, а мы, например, ожидаем что в данном свойстве по умолчанию должен быть пустой массив, к примеру

2021-10-05 16:15 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      chartsHeight.forEach(chartValue => {
при создании тимплейтов лучше отдавать предпочтение методу `map`, подробнее поговорим на занятии

2021-10-05 16:15 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      const scale = 50 / maxValue;
50 - это значение `chartHeight`

2021-10-05 16:17 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor(creationObj) {
лучше использовать значения аргументов по умолчанию вот таким образом:
```
  constructor({
    data = [],
    label = '',
    link = '',
    value = 0,
    formatHeading = data => data,
  } = {}) {
    this.data = data;
    this.label = label;
    this.link = link;
    this.value = formatHeading(value);

    this.render();
  }
```

2021-10-05 16:17 UTC, dosandk approved these changes
good 👍

2021-10-05 17:43 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-07 21:36 UTC, dosandk approved these changes
good 👍

2021-10-07 21:36 UTC, merged